# Generated by Django 6.0.2 on 2026-05-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[], max_length=10),
        ),
    ]
