# Generated by Django 6.0.2 on 2026-03-14 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_alter_community_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymembership',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='communities.community'),
        ),
    ]
