# Generated by Django 6.0.2 on 2026-05-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('POST_CREATE', 'Post Created'), ('POST_DELETE', 'Post Deleted'), ('COMMENT_CREATE', 'Comment Created'), ('PASSWORD_CHANGE', 'Password Changed')], max_length=50),
        ),
    ]
