# Generated by Django 6.0.2 on 2026-03-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='media_file',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/%d/'),
        ),
    ]
