# Generated by Django 6.0.2 on 2026-05-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polloption',
            name='option_text',
            field=models.CharField(max_length=255, verbose_name='Option Text'),
        ),
    ]
