name: prod start

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -r requirements/prod.txt

      - name: Django checks
        run: |
          python manage.py check
          python manage.py makemigrations --check --dry-run

  deploy:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        run: |
          az acr login --name luminetwork

      - name: Build Docker image
        run: |
          docker build -t luminetwork.azurecr.io/lumi_api:latest .

      - name: Push Docker image
        run: |
          docker push luminetwork.azurecr.io/lumi_api:latest

      - name: Restart App Service
        run: |
          az webapp restart \
          --name luminetwork-backend \
          --resource-group lumi_app
